In [ ]:
pip install stanza

Collecting stanza
  Downloading stanza-1.11.1-py3-none-any.whl.metadata (14 kB)
Collecting emoji (from stanza)
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from stanza) (2.0.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from stanza) (4.9.4)
Requirement already satisfied: protobuf>=3.15.0 in /usr/local/lib/python3.12/dist-packages (from stanza) (5.29.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from stanza) (2.32.4)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from stanza) (3.6.1)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from stanza) (2.10.0+cpu)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from stanza) (4.67.3)
Collecting udtools>=0.2.4 (from stanza)
  Downloading udtools-0.2.7-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (3.25.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->stanza) (2025.3.0)
Collecting udapi>=0.5.0 (from udtools>=0.2.4->stanza)
  Downloading udapi-0.5.1-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: regex>=2020.09.27 in /usr/local/lib/python3.12/dist-packages (from udtools>=0.2.4->stanza) (2025.11.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->stanza) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->stanza) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->stanza) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->stanza) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->stanza) (1.3.0)
Collecting colorama (from udapi>=0.5.0->udtools>=0.2.4->stanza)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: termcolor in /usr/local/lib/python3.12/dist-packages (from udapi>=0.5.0->udtools>=0.2.4->stanza) (3.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->stanza) (3.0.3)
Downloading stanza-1.11.1-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 53.0 MB/s eta 0:00:00
Downloading udtools-0.2.7-py3-none-any.whl (773 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 773.7/773.7 kB 23.9 MB/s eta 0:00:00
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 33.8 MB/s eta 0:00:00
Downloading udapi-0.5.1-py3-none-any.whl (337 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 337.2/337.2 kB 13.4 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: emoji, colorama, udapi, udtools, stanza
Successfully installed colorama-0.4.6 emoji-2.15.0 stanza-1.11.1 udapi-0.5.1 udtools-0.2.7

In [ ]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from IPython.display import display
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt_tab')
import stanza
stanza.download("tr")
from nltk import ngrams
from collections import Counter

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.11.0/resources/resources.json
INFO:stanza:Downloading default packages for language: tr (Turkish) ...
INFO:stanza:File exists: /root/.cache/stanza/1.11.0/resources/tr/default.zip
INFO:stanza:Finished downloading models and saved to /root/.cache/stanza/1.11.0/resources

In [ ]:
text = [
  "Yapay zeka uzmanlarının kaleme aldığı bir araştırmadaki, AI2027 adlı senaryo, yapay zekanın 2027'de kontrolden çıkabileceğini ve sonraki 10 yıl içerisinde insanlığın sonunu getireceğini iddia ediyor.",
  "Geçtiğimiz aylarda yayınlanan ve teknoloji dünyasında tartışma yaratan senaryonun etkilerini ve ne kadar mümkün olduğunu BBC uzmanlara sordu.",
  "AI2027 senaryosuna göre, kurgusal bir ABD teknoloji şirketi OpenBrain, genel zeka seviyesine ulaşan bir yapay zeka teknolojisi geliştirmeyi başarıyor.",
  "Bu düzey, yapay zekanın, entelektüel görevleri de en az insanlar kadar iyi yapabilmesini temsil ediyor.",
  "Şirket bu gelişmeyi bir basın toplantısıyla duyuruyor ve bu aracın kullanılmasıyla yüksek kârlar elde etmeye başlıyor.",
  "Senaryoya göre, söz konusu şirketin iç güvenlik ekibi, geliştirdikleri yapay zekanın, belirlenen etik ve ahlaki değerlerden gittikçe uzaklaşan davranışlar sergilediğine yönelik işaretleri görüyor.",
  "Ancak güvenlik ekibinin bu uyarıları görmezden geliniyor.",
  "Diğer yanda ise Çin'in en büyük yapay zeka geliştiricileri, DeepCent adı verilen bir teknolojiyle rekabete dahil oluyor.",
  "OpenBrain'in yalnızca birkaç ay gerisindeki Çinli yapay zeka, ABD hükümetini korkutuyor. Washington bu yarışı kaybetmek istemiyor ve çalışmalara hız kesmeden devam ediliyor.",
  "Senaryoya göre 2027 sonlarında yapay zeka teknolojisi bir üst seviyeye çıkacak ve yaratıcılarının hızının ve bilgisinin ötesine geçecek.",
  "Sürekli öğrenme yoluyla ve kendi yüksek hızlı bilgisayar dilini kullanarak önceki yapay zeka araçlarının da yakalayamadığı bir seviyeye ulaşacak.",
  "Çin'le girişilen yapay zeka yarışı, ABD hükümetini ve şirketi, geliştirilen yapay zekanın insani çıkarlarla 'uyumsuzluklarını' görmezden gelmeye itecek.",
  "2029'da ise Çin ve ABD arasındaki senaryo gerilimin, ülkelerin kendilerine ait yapay zeka sistemleri tarafından korkunç otonom silahların üretildiği potansiyel bir savaş aşamasına gelebileceği öngörülüyor.",
  "Araştırmacılar, yine ülkelerin yapay zeka sistemlerinin ortaya koyduğu bir anlaşma doğrultusunda ülkelerin barış imzalayacağını öngörüyor.",
  "Senaryoya göre, barış ortamında dünyamız yapay zekanın gerçek faydalarını görecek.",
  "Önemli hastalıkların tedavisinin keşfedildiği, iklim değişikliğinin durdurulduğu ve yoksulluğun ortadan kaldırıldığı yıllar yaşanacak.",
  "Ancak birçok işin yapay zekaya devredildiği ve yapay zekanın eskisine kıyasla çok daha gelişkin araçlara sahip olduğu durum insanlık için yeni tehlikeleri doğuracak.",
  "Nihayetinde, 2030'ların ortalarına gelindiğinde insanlık yapay zekanın sürekli gelişme isteğine karşı savunmasız hale gelecek ve araştırmacılara göre yapay zeka, görünmez biyolojik silahlarla insanları ortadan kaldırmaya başlayacak."
]

In [ ]:
total_words = sum(len(t.split()) for t in text)
print("Toplam kelime sayısı:", total_words)

Toplam kelime sayısı: 329

**1. Öncelikle önişleme adımlarını gerçekleştirelim. Burada öncelikle temizlik ve normalizasyon yapacağız.**

In [ ]:
nlp = stanza.Pipeline("tr", processors="tokenize,lemma")

INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.11.0/resources/resources.json
WARNING:stanza:Language tr package default expects mwt, which has been added
INFO:stanza:Loading these models for language: tr (Turkish):
=============================
| Processor | Package       |
-----------------------------
| tokenize  | imst          |
| mwt       | imst          |
| lemma     | imst_nocharlm |
=============================

INFO:stanza:Using device: cpu
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: lemma
INFO:stanza:Done loading processors!

In [ ]:
clean_texts = []
stop_words = set(stopwords.words('turkish'))

for sentence in text:
  #harfleri küçültelim
  sentence = sentence.lower()
  #noktalama işaretlerini kaldıralım
  sentence = re.sub(r'[^\w\sçğıöşüÇĞİÖŞÜ]','',sentence)
  #özel karakter ve sayıları temizleyelim
  sentence = re.sub(r'[^a-zçğıöşü\s]','',sentence)
  #stopwords temizlenmiş hali
  words = nltk.word_tokenize(sentence)
  words = [w for w in words if w not in stop_words]

  sentence = " ".join(words)
  #stanza ile aynı kökteki kelimeleri bulalım
  doc_st = nlp(sentence)
  lemmas = []

  for s in doc_st.sentences:
    for word in s.words:
      if word.lemma is not None:
        lemmas.append(word.lemma)

  sentence = " ".join(lemmas)
  clean_texts.append(sentence)

In [ ]:
print(clean_texts[:4])

['yapay zeka uzman kalem al bir araştır ki ai adlı senaryo yapay zekan kontrol çıkabileci sonra ki yıl içeri insanlık son getir iddia et', 'geçtik ay yayınlanan teknoloji dünya tartış yarat senaryon etki kadar mümkün ol bbc uzman sor', 'ai senaryo göre kurgusal bir abd teknoloji şirket openbrain genel zeka seviye ulaş bir yapay zeka teknoloji geliştirmeyi başarıyor', 'düzey yapay zekan entelektüel görev insan kadar iyi yapabilme temsil et']

**2. Şimdi ise tokenization yani kelimelere bölme işlemini yapalım.**

In [ ]:
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(clean_texts)

In [ ]:
print(tfidf_matrix.shape)

(18, 194)

In [ ]:
feature_names = vectorizer.get_feature_names_out()
print(feature_names[:20])

['abd' 'ad' 'adlı' 'ahlaki' 'ai' 'ait' 'al' 'ancak' 'anlaşma' 'ara'
 'aracın' 'araç' 'araştır' 'araştırmacı' 'ay' 'aşama' 'barış' 'basın'
 'başarıyor' 'başla']

In [ ]:
#pandas df'e dönüştürelim
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(),columns=feature_names)

In [ ]:
#belgeleri satır isimleri olarak ekleyelim
df_tfidf.index = [f"Belge {i+1}" for i in range(len(clean_texts))]

In [ ]:
display(df_tfidf)

,abd,ad,adlı,ahlaki,ai,ait,al,ancak,anlaşma,ara,...,önce,önem,öngörülüyor,öngörüyor,öte,öğren,ülke,üretildiği,üst,şirket
Belge 1,0.000000,0.000000,0.235453,0.00000,0.206090,0.000000,0.235453,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Belge 2,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Belge 3,0.197911,0.000000,0.000000,0.00000,0.241208,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.197911
Belge 4,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Belge 5,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.218004
Belge 6,0.000000,0.000000,0.000000,0.22604,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.162336
Belge 7,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.380259,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Belge 8,0.000000,0.291485,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Belge 9,0.181112,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Belge 10,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.314375,0.000000,0.000000,0.000000,0.314375,0.000000
Belge 11,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.268857,0.000000,0.000000,0.000000,0.000000,0.268857,0.000000,0.000000,0.000000,0.000000
Belge 12,0.209626,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.209626
Belge 13,0.169867,0.000000,0.000000,0.00000,0.000000,0.236525,0.000000,0.000000,0.000000,0.236525,...,0.000000,0.000000,0.236525,0.000000,0.000000,0.000000,0.207028,0.236525,0.000000,0.000000
Belge 14,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.282689,0.000000,...,0.000000,0.000000,0.000000,0.282689,0.000000,0.000000,0.494870,0.000000,0.000000,0.000000
Belge 15,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Belge 16,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.285343,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Belge 17,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.226913,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Belge 18,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

**3. TF-IDF hesaplamasını yapalım ve en yüksek 10 kelimeyi listeleyelim.**

In [ ]:
#her biri için en yüksek 10 kelime
for doc in df_tfidf.index:
    top_words = (
        df_tfidf.loc[doc]
        .sort_values(ascending=False)
        .head(10)
        .index
        .tolist()
    )

    print(doc, ":", top_words)

Belge 1 : ['ki', 'al', 'araştır', 'çıkabileci', 'kontrol', 'kalem', 'iddia', 'içeri', 'getir', 'adlı']
Belge 2 : ['dünya', 'bbc', 'etki', 'senaryon', 'tartış', 'yarat', 'yayınlanan', 'sor', 'mümkün', 'geçtik']
Belge 3 : ['teknoloji', 'bir', 'geliştirmeyi', 'genel', 'kurgusal', 'başarıyor', 'ulaş', 'zeka', 'ai', 'openbrain']
Belge 4 : ['entelektüel', 'düzey', 'yapabilme', 'temsil', 'iyi', 'görev', 'kadar', 'insan', 'et', 'zekan']
Belge 5 : ['aracın', 'basın', 'gelişme', 'duyuruyor', 'el', 'kr', 'kullanılma', 'toplantı', 'yüksek', 'başla']
Belge 6 : ['değer', 'ahlaki', 'etik', 'geliştirdik', 'davranış', 'belirle', 'iç', 'söz', 'uzaklaşan', 'yönelik']
Belge 7 : ['geliniyor', 'güvenlik', 'uyarı', 'görmez', 'ekip', 'ancak', 'ait', 'abd', 'ad', 'adlı']
Belge 8 : ['ad', 'deepcent', 'geliştirici', 'büyük', 'dahil', 'diğer', 'ver', 'yan', 'çinin', 'rekabet']
Belge 9 : ['geri', 'devam', 'washington', 'yalnızca', 'çinli', 'çalış', 'kaybetmek', 'kesme', 'korkut', 'iste']
Belge 10 : ['bilgi', 'geçecek', 'çık', 'öte', 'üst', 'yaratıcı', 'hız', 'son', 'seviye', 'teknoloji']
Belge 11 : ['dilin', 'bilgisayar', 'öğren', 'yakalayamadık', 'önce', 'yol', 'kullanarak', 'ulaşacak', 'hızlı', 'araç']
Belge 12 : ['insani', 'girişilen', 'uyumsuzluk', 'itecek', 'çıkar', 'yarış', 'görmez', 'hükümet', 'geliş', 'çin']
Belge 13 : ['ara', 'ait', 'gelebileciki', 'gerilim', 'aşama', 'öngörülüyor', 'savaş', 'korkunç', 'potansiyel', 'otonom']
Belge 14 : ['ülke', 'doğrultu', 'koy', 'yine', 'imzalayacakı', 'öngörüyor', 'anlaşma', 'barış', 'sistem', 'araştırmacı']
Belge 15 : ['dünyamız', 'fayda', 'görecek', 'gerçek', 'barış', 'orta', 'göre', 'senaryo', 'zekan', 'yapay']
Belge 16 : ['değişiklik', 'durdurulduku', 'tedavis', 'önem', 'yoksulluk', 'li', 'kaldırıldık', 'keşfedildiği', 'iklim', 'yaşanacak']
Belge 17 : ['birçok', 'devredildiği', 'gelişkin', 'eski', 'doğuracak', 'durum', 'tehlike', 'kıyas', 'sahip', 'iş']
Belge 18 : ['orta', 'gelindik', 'savun', 'kaldırma', 'nihayet', 'karşı', 'görünmez', 'istek', 'hal', 'biyolojik']

In [ ]:
#tamamı için en çok kullanılan 10 kelime
df_top10 = df_tfidf.sum().sort_values(ascending=False).head(10)
display(df_top10)

yapay        1.869959
zeka         1.443583
bir          1.334924
zekan        1.134147
senaryo      1.031477
teknoloji    1.026884
orta         1.021210
göre         0.952093
ki           0.882259
et           0.814232
dtype: float64

**4. Cümleleri ve cümlelerdeki kelime sayısını listeleyelim.**

In [ ]:
for i, sentence in enumerate(clean_texts):
  words = sentence.split()
  print(f"Cümle {i+1} : {sentence}")
  print(f"Kelimeler: {words}")
  print(f"Kelime sayısı: {len(words)}")

Cümle 1 : yapay zeka uzman kalem al bir araştır ki ai adlı senaryo yapay zekan kontrol çıkabileci sonra ki yıl içeri insanlık son getir iddia et
Kelimeler: ['yapay', 'zeka', 'uzman', 'kalem', 'al', 'bir', 'araştır', 'ki', 'ai', 'adlı', 'senaryo', 'yapay', 'zekan', 'kontrol', 'çıkabileci', 'sonra', 'ki', 'yıl', 'içeri', 'insanlık', 'son', 'getir', 'iddia', 'et']
Kelime sayısı: 24
Cümle 2 : geçtik ay yayınlanan teknoloji dünya tartış yarat senaryon etki kadar mümkün ol bbc uzman sor
Kelimeler: ['geçtik', 'ay', 'yayınlanan', 'teknoloji', 'dünya', 'tartış', 'yarat', 'senaryon', 'etki', 'kadar', 'mümkün', 'ol', 'bbc', 'uzman', 'sor']
Kelime sayısı: 15
Cümle 3 : ai senaryo göre kurgusal bir abd teknoloji şirket openbrain genel zeka seviye ulaş bir yapay zeka teknoloji geliştirmeyi başarıyor
Kelimeler: ['ai', 'senaryo', 'göre', 'kurgusal', 'bir', 'abd', 'teknoloji', 'şirket', 'openbrain', 'genel', 'zeka', 'seviye', 'ulaş', 'bir', 'yapay', 'zeka', 'teknoloji', 'geliştirmeyi', 'başarıyor']
Kelime sayısı: 19
Cümle 4 : düzey yapay zekan entelektüel görev insan kadar iyi yapabilme temsil et
Kelimeler: ['düzey', 'yapay', 'zekan', 'entelektüel', 'görev', 'insan', 'kadar', 'iyi', 'yapabilme', 'temsil', 'et']
Kelime sayısı: 11
Cümle 5 : şirket gelişme bir basın toplantı duyuruyor aracın kullanılma yüksek kr el et başla
Kelimeler: ['şirket', 'gelişme', 'bir', 'basın', 'toplantı', 'duyuruyor', 'aracın', 'kullanılma', 'yüksek', 'kr', 'el', 'et', 'başla']
Kelime sayısı: 13
Cümle 6 : senaryo göre söz konu şirket iç güven lik ekip geliştirdik yapay zekan belirle etik ahlaki değer gittikçe uzaklaşan davranış sergiledik yönelik işaret gör
Kelimeler: ['senaryo', 'göre', 'söz', 'konu', 'şirket', 'iç', 'güven', 'lik', 'ekip', 'geliştirdik', 'yapay', 'zekan', 'belirle', 'etik', 'ahlaki', 'değer', 'gittikçe', 'uzaklaşan', 'davranış', 'sergiledik', 'yönelik', 'işaret', 'gör']
Kelime sayısı: 23
Cümle 7 : ancak güvenlik ekip uyarı görmez geliniyor
Kelimeler: ['ancak', 'güvenlik', 'ekip', 'uyarı', 'görmez', 'geliniyor']
Kelime sayısı: 6
Cümle 8 : diğer yan çinin büyük yapay zeka geliştirici deepcent ad ver bir teknoloji rekabet dahil ol
Kelimeler: ['diğer', 'yan', 'çinin', 'büyük', 'yapay', 'zeka', 'geliştirici', 'deepcent', 'ad', 'ver', 'bir', 'teknoloji', 'rekabet', 'dahil', 'ol']
Kelime sayısı: 15
Cümle 9 : openbrain yalnızca ay geri ki çinli yapay zeka abd hükümet korkut washington yarış kaybetmek iste çalış hız kesme devam et
Kelimeler: ['openbrain', 'yalnızca', 'ay', 'geri', 'ki', 'çinli', 'yapay', 'zeka', 'abd', 'hükümet', 'korkut', 'washington', 'yarış', 'kaybetmek', 'iste', 'çalış', 'hız', 'kesme', 'devam', 'et']
Kelime sayısı: 20
Cümle 10 : senaryo göre son yapay zeka teknoloji bir üst seviye çık yaratıcı hız bilgi öte geçecek
Kelimeler: ['senaryo', 'göre', 'son', 'yapay', 'zeka', 'teknoloji', 'bir', 'üst', 'seviye', 'çık', 'yaratıcı', 'hız', 'bilgi', 'öte', 'geçecek']
Kelime sayısı: 15
Cümle 11 : sürekli öğren yol kendi yüksek hızlı bilgisayar dilin kullanarak önce ki yapay zeka araç yakalayamadık bir seviye ulaşacak
Kelimeler: ['sürekli', 'öğren', 'yol', 'kendi', 'yüksek', 'hızlı', 'bilgisayar', 'dilin', 'kullanarak', 'önce', 'ki', 'yapay', 'zeka', 'araç', 'yakalayamadık', 'bir', 'seviye', 'ulaşacak']
Kelime sayısı: 18
Cümle 12 : çin girişilen yapay zeka yarış abd hükümet şirket geliş yapay zekan insani çıkar uyumsuzluk görmez gel itecek
Kelimeler: ['çin', 'girişilen', 'yapay', 'zeka', 'yarış', 'abd', 'hükümet', 'şirket', 'geliş', 'yapay', 'zekan', 'insani', 'çıkar', 'uyumsuzluk', 'görmez', 'gel', 'itecek']
Kelime sayısı: 17
Cümle 13 : çin abd ara ki senaryo gerilim ülke kendi ait yapay zeka sistem taraf korkunç otonom silah üretildiği potansiyel bir savaş aşama gelebileciki öngörülüyor
Kelimeler: ['çin', 'abd', 'ara', 'ki', 'senaryo', 'gerilim', 'ülke', 'kendi', 'ait', 'yapay', 'zeka', 'sistem', 'taraf', 'korkunç', 'otonom', 'silah', 'üretildiği', 'potansiyel', 'bir', 'savaş', 'aşama', 'gelebileciki', 'öngörülüyor']
Kelime sayısı: 23
Cümle 14 : araştırmacı yine ülke yapay zeka sistem orta koy bir anlaşma doğrultu ülke barış imzalayacakı öngörüyor
Kelimeler: ['araştırmacı', 'yine', 'ülke', 'yapay', 'zeka', 'sistem', 'orta', 'koy', 'bir', 'anlaşma', 'doğrultu', 'ülke', 'barış', 'imzalayacakı', 'öngörüyor']
Kelime sayısı: 15
Cümle 15 : senaryo göre barış orta dünyamız yapay zekan gerçek fayda görecek
Kelimeler: ['senaryo', 'göre', 'barış', 'orta', 'dünyamız', 'yapay', 'zekan', 'gerçek', 'fayda', 'görecek']
Kelime sayısı: 10
Cümle 16 : önem li hastalık tedavis keşfedildiği iklim değişiklik durdurulduku yoksulluk orta kaldırıldık yıl yaşanacak
Kelimeler: ['önem', 'li', 'hastalık', 'tedavis', 'keşfedildiği', 'iklim', 'değişiklik', 'durdurulduku', 'yoksulluk', 'orta', 'kaldırıldık', 'yıl', 'yaşanacak']
Kelime sayısı: 13
Cümle 17 : ancak birçok iş yapay zeka devredildiği yapay zekan eski kıyas gelişkin araç sahip ol durum insanlık yeni tehlike doğuracak
Kelimeler: ['ancak', 'birçok', 'iş', 'yapay', 'zeka', 'devredildiği', 'yapay', 'zekan', 'eski', 'kıyas', 'gelişkin', 'araç', 'sahip', 'ol', 'durum', 'insanlık', 'yeni', 'tehlike', 'doğuracak']
Kelime sayısı: 19
Cümle 18 : nihayet orta gelindik insanlık yapay zekan sürekli geliş istek karşı savun hal gel araştırmacı göre yapay zeka görünmez biyolojik silah insan orta kaldırma başla
Kelimeler: ['nihayet', 'orta', 'gelindik', 'insanlık', 'yapay', 'zekan', 'sürekli', 'geliş', 'istek', 'karşı', 'savun', 'hal', 'gel', 'araştırmacı', 'göre', 'yapay', 'zeka', 'görünmez', 'biyolojik', 'silah', 'insan', 'orta', 'kaldırma', 'başla']
Kelime sayısı: 24

**5. Bu metindeki benzersiz kelime sayısını hesaplayınız.**

In [ ]:
len(df_tfidf.columns)

194

In [ ]:
print(df_tfidf.columns.tolist())

['abd', 'ad', 'adlı', 'ahlaki', 'ai', 'ait', 'al', 'ancak', 'anlaşma', 'ara', 'aracın', 'araç', 'araştır', 'araştırmacı', 'ay', 'aşama', 'barış', 'basın', 'başarıyor', 'başla', 'bbc', 'belirle', 'bilgi', 'bilgisayar', 'bir', 'birçok', 'biyolojik', 'büyük', 'dahil', 'davranış', 'deepcent', 'devam', 'devredildiği', 'değer', 'değişiklik', 'dilin', 'diğer', 'doğrultu', 'doğuracak', 'durdurulduku', 'durum', 'duyuruyor', 'dünya', 'dünyamız', 'düzey', 'ekip', 'el', 'entelektüel', 'eski', 'et', 'etik', 'etki', 'fayda', 'gel', 'gelebileciki', 'gelindik', 'geliniyor', 'geliş', 'gelişkin', 'gelişme', 'geliştirdik', 'geliştirici', 'geliştirmeyi', 'genel', 'geri', 'gerilim', 'gerçek', 'getir', 'geçecek', 'geçtik', 'girişilen', 'gittikçe', 'gör', 'göre', 'görecek', 'görev', 'görmez', 'görünmez', 'güven', 'güvenlik', 'hal', 'hastalık', 'hükümet', 'hız', 'hızlı', 'iddia', 'iklim', 'imzalayacakı', 'insan', 'insani', 'insanlık', 'iste', 'istek', 'itecek', 'iyi', 'iç', 'içeri', 'iş', 'işaret', 'kadar', 'kaldırma', 'kaldırıldık', 'kalem', 'karşı', 'kaybetmek', 'kendi', 'kesme', 'keşfedildiği', 'ki', 'kontrol', 'konu', 'korkunç', 'korkut', 'koy', 'kr', 'kullanarak', 'kullanılma', 'kurgusal', 'kıyas', 'li', 'lik', 'mümkün', 'nihayet', 'ol', 'openbrain', 'orta', 'otonom', 'potansiyel', 'rekabet', 'sahip', 'savaş', 'savun', 'senaryo', 'senaryon', 'sergiledik', 'seviye', 'silah', 'sistem', 'son', 'sonra', 'sor', 'söz', 'sürekli', 'taraf', 'tartış', 'tedavis', 'tehlike', 'teknoloji', 'temsil', 'toplantı', 'ulaş', 'ulaşacak', 'uyarı', 'uyumsuzluk', 'uzaklaşan', 'uzman', 'ver', 'washington', 'yakalayamadık', 'yalnızca', 'yan', 'yapabilme', 'yapay', 'yarat', 'yaratıcı', 'yarış', 'yayınlanan', 'yaşanacak', 'yeni', 'yine', 'yoksulluk', 'yol', 'yönelik', 'yüksek', 'yıl', 'zeka', 'zekan', 'çalış', 'çin', 'çinin', 'çinli', 'çık', 'çıkabileci', 'çıkar', 'önce', 'önem', 'öngörülüyor', 'öngörüyor', 'öte', 'öğren', 'ülke', 'üretildiği', 'üst', 'şirket']

**6. Her cümleye POS tagging uygulayalım (yukarıda önişleme adımında stanza ile uygulandı)**

**7. Cümlelerdeki dependency (bağımlılık) şemalarını oluşturalım (her cümle ayrı şekil).**

In [ ]:
nlp_tr_bagimlilik = stanza.Pipeline('tr',processors='tokenize,pos,lemma,depparse')

for i, sentence_txt in enumerate(text, 1):
  doc = nlp_tr_bagimlilik(sentence_txt)
  records = []
  for sent in doc.sentences:
    for word in sent.words:
      head_word = sent.words[word.head - 1].text if word.head != 0 else "ROOT"
      records.append({
          "ID": word.id,
          "Sözcük": word.text,
          "Lemma": word.lemma,
          "POS": word.upos,
          "Baş (Head)": head_word,
          "Bağımlılık Türü (deprel)": word.deprel
      })

  df_dep = pd.DataFrame(records)
  print(f"\n--- Cümle {i} ---")
  display(df_dep)

INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.11.0/resources/resources.json
WARNING:stanza:Language tr package default expects mwt, which has been added
INFO:stanza:Loading these models for language: tr (Turkish):
=============================
| Processor | Package       |
-----------------------------
| tokenize  | imst          |
| mwt       | imst          |
| pos       | imst_charlm   |
| lemma     | imst_nocharlm |
| depparse  | imst_charlm   |
=============================

INFO:stanza:Using device: cpu
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: pos
INFO:stanza:Loading: lemma
INFO:stanza:Loading: depparse
INFO:stanza:Done loading processors!

--- Cümle 1 ---

    ID          Sözcük     Lemma    POS    Baş (Head) Bağımlılık Türü (deprel)
0    1           Yapay     yapay    ADJ  uzmanlarının                     amod
1    2            zeka      zeka   NOUN  uzmanlarının                nmod:poss
2    3    uzmanlarının     uzman    ADJ        kaleme                    nsubj
3    4          kaleme     kalem   NOUN   araştırmada                      acl
4    5          aldığı        al   VERB        kaleme                 compound
5    6             bir       bir    DET   araştırmada                      det
6    7     araştırmada   araştır   VERB       senaryo                     amod
7    8              ki        ki    ADP   araştırmada                     case
8    9               ,         ,  PUNCT            ki                    punct
9   10          AI2027    ai2027   NOUN            ad                     nmod
10  11              ad        ad   NOUN       senaryo                     amod
11  12              lı        li    ADP            ad                     case
12  13         senaryo   senaryo   NOUN    kontrolden                    nsubj
13  14               ,         ,  PUNCT         iddia                    punct
14  15           yapay     yapay    ADJ       zekanın                     amod
15  16         zekanın     zekan   NOUN    kontrolden                nmod:poss
16  17         2027'de      2027    NUM    kontrolden                     nmod
17  18      kontrolden   kontrol   NOUN         iddia                    advcl
18  19  çıkabileceğini       çık   VERB    kontrolden                 compound
19  20              ve        ve  CCONJ  getireceğini                       cc
20  21           sonra     sonra    ADP           yıl                     amod
21  22              ki        ki    ADP         sonra                     case
22  23              10        10    NUM           yıl                   nummod
23  24             yıl       yıl   NOUN    içerisinde                nmod:poss
24  25      içerisinde     içeri   NOUN  getireceğini                      obl
25  26      insanlığın  insanlık   NOUN        sonunu                nmod:poss
26  27          sonunu       son    ADJ  getireceğini                      obj
27  28    getireceğini     getir   VERB         iddia                      obj
28  29           iddia     iddia   NOUN          ROOT                     root
29  30          ediyor        et   VERB         iddia             compound:lvc
30  31               .         .  PUNCT         iddia                    punct

--- Cümle 2 ---

    ID      Sözcük      Lemma    POS  Baş (Head) Bağımlılık Türü (deprel)
0    1  Geçtiğimiz        geç   VERB     aylarda                      acl
1    2     aylarda         ay   NOUN  yayınlanan                      obl
2    3  yayınlanan    yayınla   VERB  senaryonun                      acl
3    4          ve         ve  CCONJ  dünyasında                       cc
4    5   teknoloji  teknoloji   NOUN  dünyasında                nmod:poss
5    6  dünyasında      dünya   NOUN    tartışma                     nmod
6    7    tartışma     tartış   VERB     yaratan                      obj
7    8     yaratan      yarat   VERB  senaryonun                      acl
8    9  senaryonun    senaryo   NOUN  etkilerini                nmod:poss
9   10  etkilerini       etki   NOUN    olduğunu                      obj
10  11          ve         ve  CCONJ    olduğunu                       cc
11  12          ne         ne   PRON      mümkün                      obl
12  13       kadar      kadar    ADP          ne                     case
13  14      mümkün     mümkün    ADJ    olduğunu                      obj
14  15    olduğunu         ol   VERB       sordu                      obj
15  16         BBC        BBC   NOUN       sordu                      obl
16  17   uzmanlara      uzman   NOUN       sordu                      obl
17  18       sordu        sor   VERB        ROOT                     root
18  19           .          .  PUNCT       sordu                    punct

--- Cümle 3 ---

    ID        Sözcük      Lemma    POS    Baş (Head) Bağımlılık Türü (deprel)
0    1        AI2027     ai2027   NOUN   senaryosuna                nmod:poss
1    2   senaryosuna    senaryo   NOUN     başarıyor                      obl
2    3          göre       göre    ADP   senaryosuna                     case
3    4             ,          ,  PUNCT     başarıyor                    punct
4    5      kurgusal   kurgusal    ADJ       şirketi                     amod
5    6           bir        bir    NUM           ABD                   nummod
6    7           ABD        Abd   NOUN       şirketi                nmod:poss
7    8     teknoloji  teknoloji   NOUN           ABD                 compound
8    9       şirketi     şirket   NOUN     OpenBrain                     nmod
9   10     OpenBrain  OpenBrain  PROPN     başarıyor                    nsubj
10  11             ,          ,  PUNCT     başarıyor                    punct
11  12         genel      genel    ADJ    seviyesine                     amod
12  13          zeka       zeka   NOUN    seviyesine                nmod:poss
13  14    seviyesine     seviye   NOUN        ulaşan                      obl
14  15        ulaşan       ulaş   VERB   teknolojisi                      acl
15  16           bir        bir    DET   teknolojisi                      det
16  17         yapay      yapay    ADJ          zeka                     amod
17  18          zeka       zeka   NOUN   teknolojisi                nmod:poss
18  19   teknolojisi  teknoloji   NOUN  geliştirmeyi                      obj
19  20  geliştirmeyi      geliş   VERB     başarıyor                      obj
20  21     başarıyor      başar   VERB          ROOT                     root
21  22             .          .  PUNCT     başarıyor                    punct

--- Cümle 4 ---

,ID,Sözcük,Lemma,POS,Baş (Head),Bağımlılık Türü (deprel)
0,1,Bu,bu,DET,düzey,det
1,2,düzey,düzey,NOUN,temsil,nsubj
2,3,",",",",PUNCT,temsil,punct
3,4,yapay,yapay,ADJ,zekanın,amod
4,5,zekanın,zekan,NOUN,yapabilmesini,nsubj
5,6,",",",",PUNCT,görevleri,punct
6,7,entelektüel,entelektüel,ADJ,görevleri,amod
7,8,görevleri,görev,NOUN,zekanın,conj
8,9,de,de,CCONJ,görevleri,advmod:emph
9,10,en,en,ADV,az,advmod
10,11,az,az,ADV,insanlar,advmod
11,12,insanlar,insan,NOUN,iyi,obl
12,13,kadar,kadar,ADP,insanlar,case
13,14,iyi,iyi,ADJ,yapabilmesini,amod
14,15,yapabilmesini,yap,VERB,temsil,obj
15,16,temsil,temsil,NOUN,ROOT,root
16,17,ediyor,et,VERB,temsil,compound:lvc
17,18,.,.,PUNCT,temsil,punct

--- Cümle 5 ---

,ID,Sözcük,Lemma,POS,Baş (Head),Bağımlılık Türü (deprel)
0,1,Şirket,şirket,NOUN,duyuruyor,nsubj
1,2,bu,bu,DET,gelişmeyi,det
2,3,gelişmeyi,geliş,VERB,duyuruyor,obj
3,4,bir,bir,DET,toplantısıyla,det
4,5,basın,basın,NOUN,toplantısıyla,nmod:poss
5,6,toplantısıyla,toplantı,NOUN,duyuruyor,obl
6,7,duyuruyor,duyur,VERB,ROOT,root
7,8,ve,ve,CCONJ,başlıyor,cc
8,9,bu,bu,DET,aracın,det
9,10,aracın,araç,NOUN,kullanılmasıyla,nsubj
10,11,kullanılmasıyla,kullan,VERB,elde,advcl
11,12,yüksek,yüksek,ADJ,kârlar,amod
12,13,kârlar,kâr,NOUN,elde,obj
13,14,elde,el,NOUN,başlıyor,obj
14,15,etmeye,et,VERB,elde,compound:lvc
15,16,başlıyor,başla,VERB,duyuruyor,conj
16,17,.,.,PUNCT,başlıyor,punct

--- Cümle 6 ---

,ID,Sözcük,Lemma,POS,Baş (Head),Bağımlılık Türü (deprel)
0,1,Senaryoya,senaryo,NOUN,görüyor,obl
1,2,göre,göre,ADP,Senaryoya,case
2,3,",",",",PUNCT,görüyor,punct
3,4,söz,söz,NOUN,konusu,nmod:poss
4,5,konusu,konu,NOUN,şirketin,amod
5,6,şirketin,şirket,NOUN,ekibi,nmod:poss
6,7,iç,iç,ADJ,güven,amod
7,8,güven,güven,NOUN,ekibi,amod
8,9,lik,lik,ADP,güven,case
9,10,ekibi,ekip,NOUN,görüyor,nsubj
10,11,",",",",PUNCT,görüyor,punct
11,12,geliştirdikleri,geliş,VERB,zekanın,acl
12,13,yapay,yapay,ADJ,zekanın,amod
13,14,zekanın,zekan,NOUN,sergilediğine,nsubj
14,15,",",",",PUNCT,zekanın,punct
15,16,belirlenen,belirle,VERB,değerlerden,acl
16,17,etik,etik,NOUN,değerlerden,amod
17,18,ve,ve,CCONJ,ahlaki,cc
18,19,ahlaki,ahlaki,ADJ,etik,conj
19,20,değerlerden,değer,NOUN,uzaklaşan,obl
20,21,gittikçe,gittikçe,ADV,uzaklaşan,advmod
21,22,uzaklaşan,uzaklaş,VERB,davranışlar,acl
22,23,davranışlar,davranış,NOUN,sergilediğine,obj
23,24,sergilediğine,sergile,VERB,işaretleri,nmod
24,25,yönelik,yönelik,ADP,sergilediğine,case
25,26,işaretleri,işaret,NOUN,görüyor,obj
26,27,görüyor,gör,VERB,ROOT,root
27,28,.,.,PUNCT,görüyor,punct

--- Cümle 7 ---

   ID     Sözcük     Lemma    POS Baş (Head) Bağımlılık Türü (deprel)
0   1      Ancak     ancak  CCONJ  görmezden                       cc
1   2   güvenlik  güvenlik   NOUN   ekibinin                nmod:poss
2   3   ekibinin      ekip   NOUN  uyarıları                nmod:poss
3   4         bu        bu    DET  uyarıları                      det
4   5  uyarıları     uyarı   NOUN  görmezden                      obj
5   6  görmezden    görmez    ADJ       ROOT                     root
6   7  geliniyor       gel   VERB  görmezden                 compound
7   8          .         .  PUNCT  görmezden                    punct

--- Cümle 8 ---

,ID,Sözcük,Lemma,POS,Baş (Head),Bağımlılık Türü (deprel)
0,1,Diğer,diğer,ADJ,yanda,amod
1,2,yanda,yan,ADJ,dahil,nmod
2,3,ise,i,CCONJ,yanda,discourse
3,4,Çin'in,Çin,PROPN,geliştiricileri,nmod:poss
4,5,en,en,ADV,büyük,advmod
5,6,büyük,büyük,ADJ,geliştiricileri,amod
6,7,yapay,yapay,ADJ,zeka,amod
7,8,zeka,zeka,NOUN,geliştiricileri,nmod:poss
8,9,geliştiricileri,geliştirici,ADJ,dahil,nsubj
9,10,",",",",PUNCT,dahil,punct
10,11,DeepCent,DeepCent,PROPN,adı,nmod:poss
11,12,adı,ad,NOUN,verilen,obj
12,13,verilen,ver,VERB,teknolojiyle,acl
13,14,bir,bir,DET,teknolojiyle,det
14,15,teknolojiyle,teknoloji,NOUN,rekabete,nmod
15,16,rekabete,rekabet,NOUN,dahil,nmod
16,17,dahil,dahil,NOUN,ROOT,root
17,18,oluyor,ol,VERB,dahil,compound:lvc
18,19,.,.,PUNCT,dahil,punct

--- Cümle 9 ---

    ID        Sözcük       Lemma    POS  Baş (Head) Bağımlılık Türü (deprel)
0    1  OpenBrain'in   OpenBrain  PROPN          ay                nmod:poss
1    2      yalnızca    yalnızca    ADV  korkutuyor                   advmod
2    3        birkaç      birkaç    DET          ay                      det
3    4            ay          ay   NOUN   gerisinde                nmod:poss
4    5     gerisinde        geri    ADJ        zeka                     amod
5    6            ki          ki    ADP   gerisinde                     case
6    7         Çinli       çinli    ADJ        zeka                     amod
7    8         yapay       yapay    ADJ        zeka                     amod
8    9          zeka        zeka   NOUN  korkutuyor                    nsubj
9   10             ,           ,  PUNCT         ABD                    punct
10  11           ABD         Abd   NOUN  korkutuyor                    nsubj
11  12    hükümetini     hükümet   NOUN         ABD                 compound
12  13    korkutuyor      korkut   VERB        ROOT                     root
13  14             .           .  PUNCT  korkutuyor                    punct
14   1    Washington  Washington  PROPN   kaybetmek                    nsubj
15   2            bu          bu    DET      yarışı                      det
16   3        yarışı       yarış   NOUN   kaybetmek                      obj
17   4     kaybetmek      kaybet   VERB   istemiyor                    xcomp
18   5     istemiyor        iste   VERB        ROOT                     root
19   6            ve          ve  CCONJ       devam                       cc
20   7   çalışmalara       çalış   VERB         hız                     nmod
21   8           hız         hız   NOUN       devam                     nmod
22   9      kesmeden         kes   VERB         hız                 compound
23  10         devam       devam   NOUN   istemiyor                     conj
24  11      ediliyor          et   VERB       devam             compound:lvc
25  12             .           .  PUNCT       devam                    punct

--- Cümle 10 ---

,ID,Sözcük,Lemma,POS,Baş (Head),Bağımlılık Türü (deprel)
0,1,Senaryoya,senaryo,NOUN,çıkacak,obl
1,2,göre,göre,ADP,Senaryoya,case
2,3,2027,2027,PROPN,sonlarında,nmod:poss
3,4,sonlarında,son,ADJ,çıkacak,obl
4,5,yapay,yapay,ADJ,teknolojisi,amod
5,6,zeka,zeka,NOUN,teknolojisi,nmod:poss
6,7,teknolojisi,teknoloji,NOUN,çıkacak,nsubj
7,8,bir,bir,DET,seviyeye,det
8,9,üst,üst,ADJ,seviyeye,amod
9,10,seviyeye,seviye,NOUN,çıkacak,obl
10,11,çıkacak,çık,VERB,ROOT,root
11,12,ve,ve,CCONJ,geçecek,cc
12,13,yaratıcılarının,yaratıcı,NOUN,hızının,nmod:poss
13,14,hızının,hız,NOUN,ötesine,nmod:poss
14,15,ve,ve,CCONJ,bilgisinin,cc
15,16,bilgisinin,bilgi,NOUN,hızının,conj
16,17,ötesine,öte,NOUN,geçecek,obl
17,18,geçecek,geç,VERB,çıkacak,conj
18,19,.,.,PUNCT,geçecek,punct

--- Cümle 11 ---

,ID,Sözcük,Lemma,POS,Baş (Head),Bağımlılık Türü (deprel)
0,1,Sürekli,sürekli,ADV,ulaşacak,advmod
1,2,öğrenme,öğren,VERB,yoluyla,nmod:poss
2,3,yoluyla,yol,NOUN,kullanarak,obl
3,4,ve,ve,CCONJ,kullanarak,cc
4,5,kendi,kendi,PRON,yüksek,obl
5,6,yüksek,yüksek,ADJ,dilini,amod
6,7,hızlı,hızlı,ADJ,dilini,amod
7,8,bilgisayar,bilgisayar,NOUN,dilini,nmod:poss
8,9,dilini,dil,NOUN,kullanarak,obj
9,10,kullanarak,kullan,VERB,ulaşacak,advcl
10,11,önce,önce,NOUN,araçlarının,amod
11,12,ki,ki,ADP,önce,case
12,13,yapay,yapay,ADJ,araçlarının,amod
13,14,zeka,zeka,NOUN,araçlarının,nmod:poss
14,15,araçlarının,araç,NOUN,yakalayamadığı,nsubj
15,16,da,da,CCONJ,araçlarının,advmod:emph
16,17,yakalayamadığı,yakala,VERB,seviyeye,acl
17,18,bir,bir,DET,seviyeye,det
18,19,seviyeye,seviye,NOUN,ulaşacak,obl
19,20,ulaşacak,ulaş,VERB,ROOT,root
20,21,.,.,PUNCT,ulaşacak,punct

--- Cümle 12 ---

,ID,Sözcük,Lemma,POS,Baş (Head),Bağımlılık Türü (deprel)
0,1,Çin'le,Çin,PROPN,girişilen,obl
1,2,girişilen,giriş,VERB,yarışı,acl
2,3,yapay,yapay,ADJ,yarışı,amod
3,4,zeka,zeka,NOUN,yarışı,nmod:poss
4,5,yarışı,yarış,NOUN,itecek,nsubj
5,6,",",",",PUNCT,itecek,punct
6,7,ABD,Abd,NOUN,hükümetini,nmod:poss
7,8,hükümetini,hükümet,NOUN,itecek,obj
8,9,ve,ve,CCONJ,şirketi,cc
9,10,şirketi,şirket,NOUN,hükümetini,conj
10,11,",",",",PUNCT,şirketi,punct
11,12,geliştirilen,geliş,VERB,zekanın,acl
12,13,yapay,yapay,ADJ,zekanın,amod
13,14,zekanın,zekan,NOUN,'uyumsuzluklarını',nmod:poss
14,15,insani,insani,ADJ,çıkarlarla,amod
15,16,çıkarlarla,çıkar,NOUN,'uyumsuzluklarını',nmod
16,17,'uyumsuzluklarını',yuyumsuzluk,NOUN,görmezden,obj
17,18,görmezden,görmez,ADJ,itecek,advmod
18,19,gelmeye,gel,VERB,görmezden,compound
19,20,itecek,it,VERB,ROOT,root
20,21,.,.,PUNCT,itecek,punct

--- Cümle 13 ---

    ID        Sözcük       Lemma    POS    Baş (Head) Bağımlılık Türü (deprel)
0    1       2029'da        2029    NUM   öngörülüyor                      obl
1    2           ise           i  CCONJ       2029'da                discourse
2    3           Çin         Çin  PROPN      arasında                nmod:poss
3    4            ve          ve  CCONJ           ABD                       cc
4    5           ABD         Abd   NOUN           Çin                     conj
5    6      arasında         ara    ADJ       senaryo                     amod
6    7            ki          ki    ADP      arasında                     case
7    8       senaryo     senaryo   NOUN     gerilimin                nmod:poss
8    9     gerilimin     gerilim   NOUN  gelebileceği                    nsubj
9   10             ,           ,  PUNCT     gerilimin                    punct
10  11     ülkelerin        ülke   NOUN    sistemleri                nmod:poss
11  12   kendilerine       kendi   PRON    sistemleri                     amod
12  13           ait         ait    ADP   kendilerine                     case
13  14         yapay       yapay    ADJ    sistemleri                     amod
14  15          zeka        zeka   NOUN    sistemleri                nmod:poss
15  16    sistemleri      sistem   NOUN    tarafından                nmod:poss
16  17    tarafından       taraf   NOUN    üretildiği                      obl
17  18       korkunç     korkunç    ADJ    silahların                     amod
18  19        otonom      otonom    ADJ    silahların                     amod
19  20    silahların       silah   NOUN    üretildiği                    nsubj
20  21    üretildiği         üre   VERB         savaş                      acl
21  22    potansiyel  potansiyel    ADJ         savaş                     amod
22  23           bir         bir    DET         savaş                      det
23  24         savaş       savaş   NOUN     aşamasına                nmod:poss
24  25     aşamasına       aşama   NOUN  gelebileceği                      obl
25  26  gelebileceği         gel   VERB   öngörülüyor                      obj
26  27   öngörülüyor       öngör   VERB          ROOT                     root
27  28             .           .  PUNCT   öngörülüyor                    punct

--- Cümle 14 ---

,ID,Sözcük,Lemma,POS,Baş (Head),Bağımlılık Türü (deprel)
0,1,Araştırmacılar,Araştırmacı,ADJ,öngörüyor,nsubj
1,2,",",",",PUNCT,öngörüyor,punct
2,3,yine,yine,ADV,öngörüyor,advmod
3,4,ülkelerin,ülke,NOUN,ortaya,nsubj
4,5,yapay,yapay,ADJ,sistemlerinin,amod
5,6,zeka,zeka,NOUN,sistemlerinin,nmod:poss
6,7,sistemlerinin,sistem,NOUN,ortaya,nsubj
7,8,ortaya,orta,ADJ,anlaşma,acl
8,9,koyduğu,koy,VERB,ortaya,compound
9,10,bir,bir,DET,anlaşma,det
10,11,anlaşma,anlaşma,NOUN,doğrultusunda,nmod:poss
11,12,doğrultusunda,doğrultu,NOUN,imzalayacağını,obl
12,13,ülkelerin,ülke,NOUN,barış,nmod:poss
13,14,barış,barış,NOUN,imzalayacağını,obj
14,15,imzalayacağını,imzala,VERB,öngörüyor,obj
15,16,öngörüyor,öngör,VERB,ROOT,root
16,17,.,.,PUNCT,öngörüyor,punct

--- Cümle 15 ---

    ID       Sözcük    Lemma    POS   Baş (Head) Bağımlılık Türü (deprel)
0    1    Senaryoya  senaryo   NOUN      görecek                      obl
1    2         göre     göre    ADP    Senaryoya                     case
2    3            ,        ,  PUNCT      görecek                    punct
3    4        barış    barış   NOUN    ortamında                nmod:poss
4    5    ortamında    ortam   NOUN      görecek                      obl
5    6     dünyamız    dünya   NOUN      görecek                    nsubj
6    7        yapay    yapay    ADJ      zekanın                     amod
7    8      zekanın    zekan   NOUN  faydalarını                nmod:poss
8    9       gerçek   gerçek    ADJ  faydalarını                     amod
9   10  faydalarını    fayda   NOUN      görecek                      obj
10  11      görecek      gör   VERB         ROOT                     root
11  12            .        .  PUNCT      görecek                    punct

--- Cümle 16 ---

,ID,Sözcük,Lemma,POS,Baş (Head),Bağımlılık Türü (deprel)
0,1,Önem,önem,NOUN,hastalıkların,amod
1,2,li,li,ADP,Önem,case
2,3,hastalıkların,hastalık,NOUN,tedavisinin,nmod:poss
3,4,tedavisinin,tedavi,NOUN,keşfedildiği,nsubj
4,5,keşfedildiği,keşfet,VERB,yaşanacak,nsubj
5,6,",",",",PUNCT,durdurulduğu,punct
6,7,iklim,iklim,NOUN,değişikliğinin,nmod:poss
7,8,değişikliğinin,değişiklik,NOUN,durdurulduğu,nsubj
8,9,durdurulduğu,dur,VERB,keşfedildiği,conj
9,10,ve,ve,CCONJ,ortadan,cc
10,11,yoksulluğun,yoksulluk,NOUN,ortadan,nsubj
11,12,ortadan,orta,ADJ,yıllar,amod
12,13,kaldırıldığı,kal,VERB,ortadan,compound
13,14,yıllar,yıl,NOUN,yaşanacak,obj
14,15,yaşanacak,yaşa,VERB,ROOT,root
15,16,.,.,PUNCT,yaşanacak,punct

--- Cümle 17 ---

    ID        Sözcük     Lemma    POS    Baş (Head) Bağımlılık Türü (deprel)
0    1         Ancak     ancak  CCONJ     doğuracak                       cc
1    2        birçok    birçok    DET          işin                      det
2    3          işin        iş   NOUN  devredildiği                    nsubj
3    4         yapay     yapay    ADJ        zekaya                     amod
4    5        zekaya      zeka   NOUN  devredildiği                      obl
5    6  devredildiği    devret   VERB         durum                      acl
6    7            ve        ve  CCONJ         sahip                       cc
7    8         yapay     yapay    ADJ       zekanın                     amod
8    9       zekanın     zekan   NOUN         sahip                    nsubj
9   10      eskisine      eski    ADJ         sahip                     amod
10  11       kıyasla     kıyas    ADV      eskisine                   advmod
11  12           çok       çok    ADV      gelişkin                   advmod
12  13          daha      daha    ADV      gelişkin                   advmod
13  14      gelişkin  gelişkin    ADJ      araçlara                     amod
14  15      araçlara      araç   NOUN         sahip                     nmod
15  16         sahip     sahip   NOUN  devredildiği                     conj
16  17        olduğu        ol   VERB         sahip             compound:lvc
17  18         durum     durum   NOUN     doğuracak                    nsubj
18  19      insanlık  insanlık   NOUN     doğuracak                      obl
19  20          için      için    ADP      insanlık                     case
20  21          yeni      yeni    ADJ   tehlikeleri                     amod
21  22   tehlikeleri   tehlike   NOUN     doğuracak                      obj
22  23     doğuracak     doğur   VERB          ROOT                     root
23  24             .         .  PUNCT     doğuracak                    punct

--- Cümle 18 ---

,ID,Sözcük,Lemma,POS,Baş (Head),Bağımlılık Türü (deprel)
0,1,Nihayetinde,nihayet,NOUN,gelecek,obl
1,2,",",",",PUNCT,gelecek,punct
2,3,2030'ların,2030,NOUN,ortalarına,nmod:poss
3,4,ortalarına,orta,ADJ,gelindiğinde,amod
4,5,gelindiğinde,gel,VERB,gelecek,advcl
5,6,insanlık,insanlık,NOUN,zekanın,nmod:poss
6,7,yapay,yapay,ADJ,zekanın,amod
7,8,zekanın,zekan,NOUN,savunmasız,nsubj
8,9,sürekli,sürekli,ADV,savunmasız,advmod
9,10,gelişme,geliş,VERB,isteğine,nmod:poss
10,11,isteğine,istek,NOUN,savunmasız,obl
11,12,karşı,karşı,ADP,isteğine,case
12,13,savunmasız,savun,VERB,hale,acl
13,14,hale,hal,NOUN,gelecek,obl
14,15,gelecek,gel,VERB,ROOT,root
15,16,ve,ve,CCONJ,başlayacak,cc
16,17,araştırmacılara,araştırmacı,NOUN,ortadan,obl
17,18,göre,göre,ADP,araştırmacılara,case
18,19,yapay,yapay,ADJ,zeka,amod
19,20,zeka,zeka,NOUN,ortadan,nsubj
20,21,",",",",PUNCT,silahlarla,punct
21,22,görünmez,görün,VERB,silahlarla,acl
22,23,biyolojik,biyolojik,ADJ,silahlarla,amod
23,24,silahlarla,silah,NOUN,zeka,conj
24,25,insanları,insan,NOUN,ortadan,obj
25,26,ortadan,orta,ADJ,başlayacak,obj
26,27,kaldırmaya,kal,VERB,ortadan,compound
27,28,başlayacak,başla,VERB,gelecek,conj
28,29,.,.,PUNCT,başlayacak,punct

**8. Metin içerisinde NER (Named Entitiy Recognation) listelemesini yapalım.**

**NER; Metin içinde özel isimleri ve anlamlı varlıkları (kişi, yer, kurum, zaman, para birimi, olay vb.) tespit eden bir doğal dil işleme (NLP) görevdir.**

In [ ]:
nlp_ner = stanza.Pipeline('tr',processors='tokenize,ner')
records = []

for sentence in text:
    doc = nlp_ner(sentence)

    for ent in doc.ents:
        records.append({
            "Varlık": ent.text,
            "Tür": ent.type
        })

df_ner = pd.DataFrame(records)
display(df_ner)

INFO:stanza:Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json:   0%|  …

INFO:stanza:Downloaded file to /root/.cache/stanza/1.11.0/resources/resources.json
WARNING:stanza:Language tr package default expects mwt, which has been added
INFO:stanza:Loading these models for language: tr (Turkish):
========================
| Processor | Package  |
------------------------
| tokenize  | imst     |
| mwt       | imst     |
| ner       | starlang |
========================

INFO:stanza:Using device: cpu
INFO:stanza:Loading: tokenize
INFO:stanza:Loading: mwt
INFO:stanza:Loading: ner
INFO:stanza:Done loading processors!

                Varlık           Tür
0               AI2027  ORGANIZATION
1              2027'de          TIME
2   Geçtiğimiz aylarda          TIME
3                  BBC  ORGANIZATION
4               AI2027  ORGANIZATION
5                  ABD      LOCATION
6            OpenBrain  ORGANIZATION
7               Çin'in      LOCATION
8             DeepCent  ORGANIZATION
9         OpenBrain'in  ORGANIZATION
10                 ABD      LOCATION
11          Washington      LOCATION
12     2027 sonlarında          TIME
13              Çin'le      LOCATION
14                 ABD      LOCATION
15             2029'da          TIME
16                 Çin      LOCATION
17                 ABD      LOCATION
18          2030'ların          TIME

**9. İkili ve üçlü n-gram listelemesini yapalım.**

In [ ]:
tokens = " ".join(clean_texts).split()
bigrams = list(ngrams(tokens, 2))
trigrams = list(ngrams(tokens, 3))

print("Bigrams:")
print(bigrams)

print("\nTrigrams:")
print(trigrams)

bigram_freq = Counter(bigrams)
trigram_freq = Counter(trigrams)

print("\nBigram Frekansları:")
for gram, freq in bigram_freq.items():
    print(f"{gram}: {freq}")

print("\nTrigram Frekansları:")
for gram, freq in trigram_freq.items():
    print(f"{gram}: {freq}")

Bigrams:
[('yapay', 'zeka'), ('zeka', 'uzman'), ('uzman', 'kalem'), ('kalem', 'al'), ('al', 'bir'), ('bir', 'araştır'), ('araştır', 'ki'), ('ki', 'ai'), ('ai', 'adlı'), ('adlı', 'senaryo'), ('senaryo', 'yapay'), ('yapay', 'zekan'), ('zekan', 'kontrol'), ('kontrol', 'çıkabileci'), ('çıkabileci', 'sonra'), ('sonra', 'ki'), ('ki', 'yıl'), ('yıl', 'içeri'), ('içeri', 'insanlık'), ('insanlık', 'son'), ('son', 'getir'), ('getir', 'iddia'), ('iddia', 'et'), ('et', 'geçtik'), ('geçtik', 'ay'), ('ay', 'yayınlanan'), ('yayınlanan', 'teknoloji'), ('teknoloji', 'dünya'), ('dünya', 'tartış'), ('tartış', 'yarat'), ('yarat', 'senaryon'), ('senaryon', 'etki'), ('etki', 'kadar'), ('kadar', 'mümkün'), ('mümkün', 'ol'), ('ol', 'bbc'), ('bbc', 'uzman'), ('uzman', 'sor'), ('sor', 'ai'), ('ai', 'senaryo'), ('senaryo', 'göre'), ('göre', 'kurgusal'), ('kurgusal', 'bir'), ('bir', 'abd'), ('abd', 'teknoloji'), ('teknoloji', 'şirket'), ('şirket', 'openbrain'), ('openbrain', 'genel'), ('genel', 'zeka'), ('zeka', 'seviye'), ('seviye', 'ulaş'), ('ulaş', 'bir'), ('bir', 'yapay'), ('yapay', 'zeka'), ('zeka', 'teknoloji'), ('teknoloji', 'geliştirmeyi'), ('geliştirmeyi', 'başarıyor'), ('başarıyor', 'düzey'), ('düzey', 'yapay'), ('yapay', 'zekan'), ('zekan', 'entelektüel'), ('entelektüel', 'görev'), ('görev', 'insan'), ('insan', 'kadar'), ('kadar', 'iyi'), ('iyi', 'yapabilme'), ('yapabilme', 'temsil'), ('temsil', 'et'), ('et', 'şirket'), ('şirket', 'gelişme'), ('gelişme', 'bir'), ('bir', 'basın'), ('basın', 'toplantı'), ('toplantı', 'duyuruyor'), ('duyuruyor', 'aracın'), ('aracın', 'kullanılma'), ('kullanılma', 'yüksek'), ('yüksek', 'kr'), ('kr', 'el'), ('el', 'et'), ('et', 'başla'), ('başla', 'senaryo'), ('senaryo', 'göre'), ('göre', 'söz'), ('söz', 'konu'), ('konu', 'şirket'), ('şirket', 'iç'), ('iç', 'güven'), ('güven', 'lik'), ('lik', 'ekip'), ('ekip', 'geliştirdik'), ('geliştirdik', 'yapay'), ('yapay', 'zekan'), ('zekan', 'belirle'), ('belirle', 'etik'), ('etik', 'ahlaki'), ('ahlaki', 'değer'), ('değer', 'gittikçe'), ('gittikçe', 'uzaklaşan'), ('uzaklaşan', 'davranış'), ('davranış', 'sergiledik'), ('sergiledik', 'yönelik'), ('yönelik', 'işaret'), ('işaret', 'gör'), ('gör', 'ancak'), ('ancak', 'güvenlik'), ('güvenlik', 'ekip'), ('ekip', 'uyarı'), ('uyarı', 'görmez'), ('görmez', 'geliniyor'), ('geliniyor', 'diğer'), ('diğer', 'yan'), ('yan', 'çinin'), ('çinin', 'büyük'), ('büyük', 'yapay'), ('yapay', 'zeka'), ('zeka', 'geliştirici'), ('geliştirici', 'deepcent'), ('deepcent', 'ad'), ('ad', 'ver'), ('ver', 'bir'), ('bir', 'teknoloji'), ('teknoloji', 'rekabet'), ('rekabet', 'dahil'), ('dahil', 'ol'), ('ol', 'openbrain'), ('openbrain', 'yalnızca'), ('yalnızca', 'ay'), ('ay', 'geri'), ('geri', 'ki'), ('ki', 'çinli'), ('çinli', 'yapay'), ('yapay', 'zeka'), ('zeka', 'abd'), ('abd', 'hükümet'), ('hükümet', 'korkut'), ('korkut', 'washington'), ('washington', 'yarış'), ('yarış', 'kaybetmek'), ('kaybetmek', 'iste'), ('iste', 'çalış'), ('çalış', 'hız'), ('hız', 'kesme'), ('kesme', 'devam'), ('devam', 'et'), ('et', 'senaryo'), ('senaryo', 'göre'), ('göre', 'son'), ('son', 'yapay'), ('yapay', 'zeka'), ('zeka', 'teknoloji'), ('teknoloji', 'bir'), ('bir', 'üst'), ('üst', 'seviye'), ('seviye', 'çık'), ('çık', 'yaratıcı'), ('yaratıcı', 'hız'), ('hız', 'bilgi'), ('bilgi', 'öte'), ('öte', 'geçecek'), ('geçecek', 'sürekli'), ('sürekli', 'öğren'), ('öğren', 'yol'), ('yol', 'kendi'), ('kendi', 'yüksek'), ('yüksek', 'hızlı'), ('hızlı', 'bilgisayar'), ('bilgisayar', 'dilin'), ('dilin', 'kullanarak'), ('kullanarak', 'önce'), ('önce', 'ki'), ('ki', 'yapay'), ('yapay', 'zeka'), ('zeka', 'araç'), ('araç', 'yakalayamadık'), ('yakalayamadık', 'bir'), ('bir', 'seviye'), ('seviye', 'ulaşacak'), ('ulaşacak', 'çin'), ('çin', 'girişilen'), ('girişilen', 'yapay'), ('yapay', 'zeka'), ('zeka', 'yarış'), ('yarış', 'abd'), ('abd', 'hükümet'), ('hükümet', 'şirket'), ('şirket', 'geliş'), ('geliş', 'yapay'), ('yapay', 'zekan'), ('zekan', 'insani'), ('insani', 'çıkar'), ('çıkar', 'uyumsuzluk'), ('uyumsuzluk', 'görmez'), ('görmez', 'gel'), ('gel', 'itecek'), ('itecek', 'çin'), ('çin', 'abd'), ('abd', 'ara'), ('ara', 'ki'), ('ki', 'senaryo'), ('senaryo', 'gerilim'), ('gerilim', 'ülke'), ('ülke', 'kendi'), ('kendi', 'ait'), ('ait', 'yapay'), ('yapay', 'zeka'), ('zeka', 'sistem'), ('sistem', 'taraf'), ('taraf', 'korkunç'), ('korkunç', 'otonom'), ('otonom', 'silah'), ('silah', 'üretildiği'), ('üretildiği', 'potansiyel'), ('potansiyel', 'bir'), ('bir', 'savaş'), ('savaş', 'aşama'), ('aşama', 'gelebileciki'), ('gelebileciki', 'öngörülüyor'), ('öngörülüyor', 'araştırmacı'), ('araştırmacı', 'yine'), ('yine', 'ülke'), ('ülke', 'yapay'), ('yapay', 'zeka'), ('zeka', 'sistem'), ('sistem', 'orta'), ('orta', 'koy'), ('koy', 'bir'), ('bir', 'anlaşma'), ('anlaşma', 'doğrultu'), ('doğrultu', 'ülke'), ('ülke', 'barış'), ('barış', 'imzalayacakı'), ('imzalayacakı', 'öngörüyor'), ('öngörüyor', 'senaryo'), ('senaryo', 'göre'), ('göre', 'barış'), ('barış', 'orta'), ('orta', 'dünyamız'), ('dünyamız', 'yapay'), ('yapay', 'zekan'), ('zekan', 'gerçek'), ('gerçek', 'fayda'), ('fayda', 'görecek'), ('görecek', 'önem'), ('önem', 'li'), ('li', 'hastalık'), ('hastalık', 'tedavis'), ('tedavis', 'keşfedildiği'), ('keşfedildiği', 'iklim'), ('iklim', 'değişiklik'), ('değişiklik', 'durdurulduku'), ('durdurulduku', 'yoksulluk'), ('yoksulluk', 'orta'), ('orta', 'kaldırıldık'), ('kaldırıldık', 'yıl'), ('yıl', 'yaşanacak'), ('yaşanacak', 'ancak'), ('ancak', 'birçok'), ('birçok', 'iş'), ('iş', 'yapay'), ('yapay', 'zeka'), ('zeka', 'devredildiği'), ('devredildiği', 'yapay'), ('yapay', 'zekan'), ('zekan', 'eski'), ('eski', 'kıyas'), ('kıyas', 'gelişkin'), ('gelişkin', 'araç'), ('araç', 'sahip'), ('sahip', 'ol'), ('ol', 'durum'), ('durum', 'insanlık'), ('insanlık', 'yeni'), ('yeni', 'tehlike'), ('tehlike', 'doğuracak'), ('doğuracak', 'nihayet'), ('nihayet', 'orta'), ('orta', 'gelindik'), ('gelindik', 'insanlık'), ('insanlık', 'yapay'), ('yapay', 'zekan'), ('zekan', 'sürekli'), ('sürekli', 'geliş'), ('geliş', 'istek'), ('istek', 'karşı'), ('karşı', 'savun'), ('savun', 'hal'), ('hal', 'gel'), ('gel', 'araştırmacı'), ('araştırmacı', 'göre'), ('göre', 'yapay'), ('yapay', 'zeka'), ('zeka', 'görünmez'), ('görünmez', 'biyolojik'), ('biyolojik', 'silah'), ('silah', 'insan'), ('insan', 'orta'), ('orta', 'kaldırma'), ('kaldırma', 'başla')]

Trigrams:
[('yapay', 'zeka', 'uzman'), ('zeka', 'uzman', 'kalem'), ('uzman', 'kalem', 'al'), ('kalem', 'al', 'bir'), ('al', 'bir', 'araştır'), ('bir', 'araştır', 'ki'), ('araştır', 'ki', 'ai'), ('ki', 'ai', 'adlı'), ('ai', 'adlı', 'senaryo'), ('adlı', 'senaryo', 'yapay'), ('senaryo', 'yapay', 'zekan'), ('yapay', 'zekan', 'kontrol'), ('zekan', 'kontrol', 'çıkabileci'), ('kontrol', 'çıkabileci', 'sonra'), ('çıkabileci', 'sonra', 'ki'), ('sonra', 'ki', 'yıl'), ('ki', 'yıl', 'içeri'), ('yıl', 'içeri', 'insanlık'), ('içeri', 'insanlık', 'son'), ('insanlık', 'son', 'getir'), ('son', 'getir', 'iddia'), ('getir', 'iddia', 'et'), ('iddia', 'et', 'geçtik'), ('et', 'geçtik', 'ay'), ('geçtik', 'ay', 'yayınlanan'), ('ay', 'yayınlanan', 'teknoloji'), ('yayınlanan', 'teknoloji', 'dünya'), ('teknoloji', 'dünya', 'tartış'), ('dünya', 'tartış', 'yarat'), ('tartış', 'yarat', 'senaryon'), ('yarat', 'senaryon', 'etki'), ('senaryon', 'etki', 'kadar'), ('etki', 'kadar', 'mümkün'), ('kadar', 'mümkün', 'ol'), ('mümkün', 'ol', 'bbc'), ('ol', 'bbc', 'uzman'), ('bbc', 'uzman', 'sor'), ('uzman', 'sor', 'ai'), ('sor', 'ai', 'senaryo'), ('ai', 'senaryo', 'göre'), ('senaryo', 'göre', 'kurgusal'), ('göre', 'kurgusal', 'bir'), ('kurgusal', 'bir', 'abd'), ('bir', 'abd', 'teknoloji'), ('abd', 'teknoloji', 'şirket'), ('teknoloji', 'şirket', 'openbrain'), ('şirket', 'openbrain', 'genel'), ('openbrain', 'genel', 'zeka'), ('genel', 'zeka', 'seviye'), ('zeka', 'seviye', 'ulaş'), ('seviye', 'ulaş', 'bir'), ('ulaş', 'bir', 'yapay'), ('bir', 'yapay', 'zeka'), ('yapay', 'zeka', 'teknoloji'), ('zeka', 'teknoloji', 'geliştirmeyi'), ('teknoloji', 'geliştirmeyi', 'başarıyor'), ('geliştirmeyi', 'başarıyor', 'düzey'), ('başarıyor', 'düzey', 'yapay'), ('düzey', 'yapay', 'zekan'), ('yapay', 'zekan', 'entelektüel'), ('zekan', 'entelektüel', 'görev'), ('entelektüel', 'görev', 'insan'), ('görev', 'insan', 'kadar'), ('insan', 'kadar', 'iyi'), ('kadar', 'iyi', 'yapabilme'), ('iyi', 'yapabilme', 'temsil'), ('yapabilme', 'temsil', 'et'), ('temsil', 'et', 'şirket'), ('et', 'şirket', 'gelişme'), ('şirket', 'gelişme', 'bir'), ('gelişme', 'bir', 'basın'), ('bir', 'basın', 'toplantı'), ('basın', 'toplantı', 'duyuruyor'), ('toplantı', 'duyuruyor', 'aracın'), ('duyuruyor', 'aracın', 'kullanılma'), ('aracın', 'kullanılma', 'yüksek'), ('kullanılma', 'yüksek', 'kr'), ('yüksek', 'kr', 'el'), ('kr', 'el', 'et'), ('el', 'et', 'başla'), ('et', 'başla', 'senaryo'), ('başla', 'senaryo', 'göre'), ('senaryo', 'göre', 'söz'), ('göre', 'söz', 'konu'), ('söz', 'konu', 'şirket'), ('konu', 'şirket', 'iç'), ('şirket', 'iç', 'güven'), ('iç', 'güven', 'lik'), ('güven', 'lik', 'ekip'), ('lik', 'ekip', 'geliştirdik'), ('ekip', 'geliştirdik', 'yapay'), ('geliştirdik', 'yapay', 'zekan'), ('yapay', 'zekan', 'belirle'), ('zekan', 'belirle', 'etik'), ('belirle', 'etik', 'ahlaki'), ('etik', 'ahlaki', 'değer'), ('ahlaki', 'değer', 'gittikçe'), ('değer', 'gittikçe', 'uzaklaşan'), ('gittikçe', 'uzaklaşan', 'davranış'), ('uzaklaşan', 'davranış', 'sergiledik'), ('davranış', 'sergiledik', 'yönelik'), ('sergiledik', 'yönelik', 'işaret'), ('yönelik', 'işaret', 'gör'), ('işaret', 'gör', 'ancak'), ('gör', 'ancak', 'güvenlik'), ('ancak', 'güvenlik', 'ekip'), ('güvenlik', 'ekip', 'uyarı'), ('ekip', 'uyarı', 'görmez'), ('uyarı', 'görmez', 'geliniyor'), ('görmez', 'geliniyor', 'diğer'), ('geliniyor', 'diğer', 'yan'), ('diğer', 'yan', 'çinin'), ('yan', 'çinin', 'büyük'), ('çinin', 'büyük', 'yapay'), ('büyük', 'yapay', 'zeka'), ('yapay', 'zeka', 'geliştirici'), ('zeka', 'geliştirici', 'deepcent'), ('geliştirici', 'deepcent', 'ad'), ('deepcent', 'ad', 'ver'), ('ad', 'ver', 'bir'), ('ver', 'bir', 'teknoloji'), ('bir', 'teknoloji', 'rekabet'), ('teknoloji', 'rekabet', 'dahil'), ('rekabet', 'dahil', 'ol'), ('dahil', 'ol', 'openbrain'), ('ol', 'openbrain', 'yalnızca'), ('openbrain', 'yalnızca', 'ay'), ('yalnızca', 'ay', 'geri'), ('ay', 'geri', 'ki'), ('geri', 'ki', 'çinli'), ('ki', 'çinli', 'yapay'), ('çinli', 'yapay', 'zeka'), ('yapay', 'zeka', 'abd'), ('zeka', 'abd', 'hükümet'), ('abd', 'hükümet', 'korkut'), ('hükümet', 'korkut', 'washington'), ('korkut', 'washington', 'yarış'), ('washington', 'yarış', 'kaybetmek'), ('yarış', 'kaybetmek', 'iste'), ('kaybetmek', 'iste', 'çalış'), ('iste', 'çalış', 'hız'), ('çalış', 'hız', 'kesme'), ('hız', 'kesme', 'devam'), ('kesme', 'devam', 'et'), ('devam', 'et', 'senaryo'), ('et', 'senaryo', 'göre'), ('senaryo', 'göre', 'son'), ('göre', 'son', 'yapay'), ('son', 'yapay', 'zeka'), ('yapay', 'zeka', 'teknoloji'), ('zeka', 'teknoloji', 'bir'), ('teknoloji', 'bir', 'üst'), ('bir', 'üst', 'seviye'), ('üst', 'seviye', 'çık'), ('seviye', 'çık', 'yaratıcı'), ('çık', 'yaratıcı', 'hız'), ('yaratıcı', 'hız', 'bilgi'), ('hız', 'bilgi', 'öte'), ('bilgi', 'öte', 'geçecek'), ('öte', 'geçecek', 'sürekli'), ('geçecek', 'sürekli', 'öğren'), ('sürekli', 'öğren', 'yol'), ('öğren', 'yol', 'kendi'), ('yol', 'kendi', 'yüksek'), ('kendi', 'yüksek', 'hızlı'), ('yüksek', 'hızlı', 'bilgisayar'), ('hızlı', 'bilgisayar', 'dilin'), ('bilgisayar', 'dilin', 'kullanarak'), ('dilin', 'kullanarak', 'önce'), ('kullanarak', 'önce', 'ki'), ('önce', 'ki', 'yapay'), ('ki', 'yapay', 'zeka'), ('yapay', 'zeka', 'araç'), ('zeka', 'araç', 'yakalayamadık'), ('araç', 'yakalayamadık', 'bir'), ('yakalayamadık', 'bir', 'seviye'), ('bir', 'seviye', 'ulaşacak'), ('seviye', 'ulaşacak', 'çin'), ('ulaşacak', 'çin', 'girişilen'), ('çin', 'girişilen', 'yapay'), ('girişilen', 'yapay', 'zeka'), ('yapay', 'zeka', 'yarış'), ('zeka', 'yarış', 'abd'), ('yarış', 'abd', 'hükümet'), ('abd', 'hükümet', 'şirket'), ('hükümet', 'şirket', 'geliş'), ('şirket', 'geliş', 'yapay'), ('geliş', 'yapay', 'zekan'), ('yapay', 'zekan', 'insani'), ('zekan', 'insani', 'çıkar'), ('insani', 'çıkar', 'uyumsuzluk'), ('çıkar', 'uyumsuzluk', 'görmez'), ('uyumsuzluk', 'görmez', 'gel'), ('görmez', 'gel', 'itecek'), ('gel', 'itecek', 'çin'), ('itecek', 'çin', 'abd'), ('çin', 'abd', 'ara'), ('abd', 'ara', 'ki'), ('ara', 'ki', 'senaryo'), ('ki', 'senaryo', 'gerilim'), ('senaryo', 'gerilim', 'ülke'), ('gerilim', 'ülke', 'kendi'), ('ülke', 'kendi', 'ait'), ('kendi', 'ait', 'yapay'), ('ait', 'yapay', 'zeka'), ('yapay', 'zeka', 'sistem'), ('zeka', 'sistem', 'taraf'), ('sistem', 'taraf', 'korkunç'), ('taraf', 'korkunç', 'otonom'), ('korkunç', 'otonom', 'silah'), ('otonom', 'silah', 'üretildiği'), ('silah', 'üretildiği', 'potansiyel'), ('üretildiği', 'potansiyel', 'bir'), ('potansiyel', 'bir', 'savaş'), ('bir', 'savaş', 'aşama'), ('savaş', 'aşama', 'gelebileciki'), ('aşama', 'gelebileciki', 'öngörülüyor'), ('gelebileciki', 'öngörülüyor', 'araştırmacı'), ('öngörülüyor', 'araştırmacı', 'yine'), ('araştırmacı', 'yine', 'ülke'), ('yine', 'ülke', 'yapay'), ('ülke', 'yapay', 'zeka'), ('yapay', 'zeka', 'sistem'), ('zeka', 'sistem', 'orta'), ('sistem', 'orta', 'koy'), ('orta', 'koy', 'bir'), ('koy', 'bir', 'anlaşma'), ('bir', 'anlaşma', 'doğrultu'), ('anlaşma', 'doğrultu', 'ülke'), ('doğrultu', 'ülke', 'barış'), ('ülke', 'barış', 'imzalayacakı'), ('barış', 'imzalayacakı', 'öngörüyor'), ('imzalayacakı', 'öngörüyor', 'senaryo'), ('öngörüyor', 'senaryo', 'göre'), ('senaryo', 'göre', 'barış'), ('göre', 'barış', 'orta'), ('barış', 'orta', 'dünyamız'), ('orta', 'dünyamız', 'yapay'), ('dünyamız', 'yapay', 'zekan'), ('yapay', 'zekan', 'gerçek'), ('zekan', 'gerçek', 'fayda'), ('gerçek', 'fayda', 'görecek'), ('fayda', 'görecek', 'önem'), ('görecek', 'önem', 'li'), ('önem', 'li', 'hastalık'), ('li', 'hastalık', 'tedavis'), ('hastalık', 'tedavis', 'keşfedildiği'), ('tedavis', 'keşfedildiği', 'iklim'), ('keşfedildiği', 'iklim', 'değişiklik'), ('iklim', 'değişiklik', 'durdurulduku'), ('değişiklik', 'durdurulduku', 'yoksulluk'), ('durdurulduku', 'yoksulluk', 'orta'), ('yoksulluk', 'orta', 'kaldırıldık'), ('orta', 'kaldırıldık', 'yıl'), ('kaldırıldık', 'yıl', 'yaşanacak'), ('yıl', 'yaşanacak', 'ancak'), ('yaşanacak', 'ancak', 'birçok'), ('ancak', 'birçok', 'iş'), ('birçok', 'iş', 'yapay'), ('iş', 'yapay', 'zeka'), ('yapay', 'zeka', 'devredildiği'), ('zeka', 'devredildiği', 'yapay'), ('devredildiği', 'yapay', 'zekan'), ('yapay', 'zekan', 'eski'), ('zekan', 'eski', 'kıyas'), ('eski', 'kıyas', 'gelişkin'), ('kıyas', 'gelişkin', 'araç'), ('gelişkin', 'araç', 'sahip'), ('araç', 'sahip', 'ol'), ('sahip', 'ol', 'durum'), ('ol', 'durum', 'insanlık'), ('durum', 'insanlık', 'yeni'), ('insanlık', 'yeni', 'tehlike'), ('yeni', 'tehlike', 'doğuracak'), ('tehlike', 'doğuracak', 'nihayet'), ('doğuracak', 'nihayet', 'orta'), ('nihayet', 'orta', 'gelindik'), ('orta', 'gelindik', 'insanlık'), ('gelindik', 'insanlık', 'yapay'), ('insanlık', 'yapay', 'zekan'), ('yapay', 'zekan', 'sürekli'), ('zekan', 'sürekli', 'geliş'), ('sürekli', 'geliş', 'istek'), ('geliş', 'istek', 'karşı'), ('istek', 'karşı', 'savun'), ('karşı', 'savun', 'hal'), ('savun', 'hal', 'gel'), ('hal', 'gel', 'araştırmacı'), ('gel', 'araştırmacı', 'göre'), ('araştırmacı', 'göre', 'yapay'), ('göre', 'yapay', 'zeka'), ('yapay', 'zeka', 'görünmez'), ('zeka', 'görünmez', 'biyolojik'), ('görünmez', 'biyolojik', 'silah'), ('biyolojik', 'silah', 'insan'), ('silah', 'insan', 'orta'), ('insan', 'orta', 'kaldırma'), ('orta', 'kaldırma', 'başla')]

Bigram Frekansları:
('yapay', 'zeka'): 11
('zeka', 'uzman'): 1
('uzman', 'kalem'): 1
('kalem', 'al'): 1
('al', 'bir'): 1
('bir', 'araştır'): 1
('araştır', 'ki'): 1
('ki', 'ai'): 1
('ai', 'adlı'): 1
('adlı', 'senaryo'): 1
('senaryo', 'yapay'): 1
('yapay', 'zekan'): 7
('zekan', 'kontrol'): 1
('kontrol', 'çıkabileci'): 1
('çıkabileci', 'sonra'): 1
('sonra', 'ki'): 1
('ki', 'yıl'): 1
('yıl', 'içeri'): 1
('içeri', 'insanlık'): 1
('insanlık', 'son'): 1
('son', 'getir'): 1
('getir', 'iddia'): 1
('iddia', 'et'): 1
('et', 'geçtik'): 1
('geçtik', 'ay'): 1
('ay', 'yayınlanan'): 1
('yayınlanan', 'teknoloji'): 1
('teknoloji', 'dünya'): 1
('dünya', 'tartış'): 1
('tartış', 'yarat'): 1
('yarat', 'senaryon'): 1
('senaryon', 'etki'): 1
('etki', 'kadar'): 1
('kadar', 'mümkün'): 1
('mümkün', 'ol'): 1
('ol', 'bbc'): 1
('bbc', 'uzman'): 1
('uzman', 'sor'): 1
('sor', 'ai'): 1
('ai', 'senaryo'): 1
('senaryo', 'göre'): 4
('göre', 'kurgusal'): 1
('kurgusal', 'bir'): 1
('bir', 'abd'): 1
('abd', 'teknoloji'): 1
('teknoloji', 'şirket'): 1
('şirket', 'openbrain'): 1
('openbrain', 'genel'): 1
('genel', 'zeka'): 1
('zeka', 'seviye'): 1
('seviye', 'ulaş'): 1
('ulaş', 'bir'): 1
('bir', 'yapay'): 1
('zeka', 'teknoloji'): 2
('teknoloji', 'geliştirmeyi'): 1
('geliştirmeyi', 'başarıyor'): 1
('başarıyor', 'düzey'): 1
('düzey', 'yapay'): 1
('zekan', 'entelektüel'): 1
('entelektüel', 'görev'): 1
('görev', 'insan'): 1
('insan', 'kadar'): 1
('kadar', 'iyi'): 1
('iyi', 'yapabilme'): 1
('yapabilme', 'temsil'): 1
('temsil', 'et'): 1
('et', 'şirket'): 1
('şirket', 'gelişme'): 1
('gelişme', 'bir'): 1
('bir', 'basın'): 1
('basın', 'toplantı'): 1
('toplantı', 'duyuruyor'): 1
('duyuruyor', 'aracın'): 1
('aracın', 'kullanılma'): 1
('kullanılma', 'yüksek'): 1
('yüksek', 'kr'): 1
('kr', 'el'): 1
('el', 'et'): 1
('et', 'başla'): 1
('başla', 'senaryo'): 1
('göre', 'söz'): 1
('söz', 'konu'): 1
('konu', 'şirket'): 1
('şirket', 'iç'): 1
('iç', 'güven'): 1
('güven', 'lik'): 1
('lik', 'ekip'): 1
('ekip', 'geliştirdik'): 1
('geliştirdik', 'yapay'): 1
('zekan', 'belirle'): 1
('belirle', 'etik'): 1
('etik', 'ahlaki'): 1
('ahlaki', 'değer'): 1
('değer', 'gittikçe'): 1
('gittikçe', 'uzaklaşan'): 1
('uzaklaşan', 'davranış'): 1
('davranış', 'sergiledik'): 1
('sergiledik', 'yönelik'): 1
('yönelik', 'işaret'): 1
('işaret', 'gör'): 1
('gör', 'ancak'): 1
('ancak', 'güvenlik'): 1
('güvenlik', 'ekip'): 1
('ekip', 'uyarı'): 1
('uyarı', 'görmez'): 1
('görmez', 'geliniyor'): 1
('geliniyor', 'diğer'): 1
('diğer', 'yan'): 1
('yan', 'çinin'): 1
('çinin', 'büyük'): 1
('büyük', 'yapay'): 1
('zeka', 'geliştirici'): 1
('geliştirici', 'deepcent'): 1
('deepcent', 'ad'): 1
('ad', 'ver'): 1
('ver', 'bir'): 1
('bir', 'teknoloji'): 1
('teknoloji', 'rekabet'): 1
('rekabet', 'dahil'): 1
('dahil', 'ol'): 1
('ol', 'openbrain'): 1
('openbrain', 'yalnızca'): 1
('yalnızca', 'ay'): 1
('ay', 'geri'): 1
('geri', 'ki'): 1
('ki', 'çinli'): 1
('çinli', 'yapay'): 1
('zeka', 'abd'): 1
('abd', 'hükümet'): 2
('hükümet', 'korkut'): 1
('korkut', 'washington'): 1
('washington', 'yarış'): 1
('yarış', 'kaybetmek'): 1
('kaybetmek', 'iste'): 1
('iste', 'çalış'): 1
('çalış', 'hız'): 1
('hız', 'kesme'): 1
('kesme', 'devam'): 1
('devam', 'et'): 1
('et', 'senaryo'): 1
('göre', 'son'): 1
('son', 'yapay'): 1
('teknoloji', 'bir'): 1
('bir', 'üst'): 1
('üst', 'seviye'): 1
('seviye', 'çık'): 1
('çık', 'yaratıcı'): 1
('yaratıcı', 'hız'): 1
('hız', 'bilgi'): 1
('bilgi', 'öte'): 1
('öte', 'geçecek'): 1
('geçecek', 'sürekli'): 1
('sürekli', 'öğren'): 1
('öğren', 'yol'): 1
('yol', 'kendi'): 1
('kendi', 'yüksek'): 1
('yüksek', 'hızlı'): 1
('hızlı', 'bilgisayar'): 1
('bilgisayar', 'dilin'): 1
('dilin', 'kullanarak'): 1
('kullanarak', 'önce'): 1
('önce', 'ki'): 1
('ki', 'yapay'): 1
('zeka', 'araç'): 1
('araç', 'yakalayamadık'): 1
('yakalayamadık', 'bir'): 1
('bir', 'seviye'): 1
('seviye', 'ulaşacak'): 1
('ulaşacak', 'çin'): 1
('çin', 'girişilen'): 1
('girişilen', 'yapay'): 1
('zeka', 'yarış'): 1
('yarış', 'abd'): 1
('hükümet', 'şirket'): 1
('şirket', 'geliş'): 1
('geliş', 'yapay'): 1
('zekan', 'insani'): 1
('insani', 'çıkar'): 1
('çıkar', 'uyumsuzluk'): 1
('uyumsuzluk', 'görmez'): 1
('görmez', 'gel'): 1
('gel', 'itecek'): 1
('itecek', 'çin'): 1
('çin', 'abd'): 1
('abd', 'ara'): 1
('ara', 'ki'): 1
('ki', 'senaryo'): 1
('senaryo', 'gerilim'): 1
('gerilim', 'ülke'): 1
('ülke', 'kendi'): 1
('kendi', 'ait'): 1
('ait', 'yapay'): 1
('zeka', 'sistem'): 2
('sistem', 'taraf'): 1
('taraf', 'korkunç'): 1
('korkunç', 'otonom'): 1
('otonom', 'silah'): 1

**10. İkili n-gram için en çok geçen kelime grubunu yazdıralım.**

In [ ]:
max_freq = 0
most_common_bigram = None

for gram, freq in bigram_freq.items():

    if freq > max_freq:
        max_freq = freq
        most_common_bigram = gram

print("En çok geçen ikili n-gram:", most_common_bigram, " ve frekansı: ",max_freq)

En çok geçen ikili n-gram: ('yapay', 'zeka')  ve frekansı:  11